name: Deploy
on:
  push:
    branches:    
      - 'main'
  workflow_run:
    workflows: ["Collect Data"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy Shiny
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install dependencies
        run: |
          install.packages("rsconnect")
          install.packages(c('tidyverse', 'shiny'))
        shell: Rscript {0}
        
      - name: Push to shinyapps.io
        run: |
          rsconnect::setAccountInfo(name='aleixalcacer', token='4D309DAA483BB3B94D4B0B05C65A5E37', secret='${{ secrets.SHINYAPPS }}')
          rsconnect::deployApp(appName = 'wordleCAT')
        shell: Rscript {0}
